export const pastWork= [
    {title: "amongus",
    subtitle: "red sus wtf",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    image: "../src/icon.png",
    link: "https://www.innersloth.com/",
    },
    {title: "amongus",
    subtitle: "red sus wtf",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    image: "../src/icon.png",
    link: "https://www.innersloth.com/",
    },
    {title: "amongus",
    subtitle: "red sus wtf",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    image: "../src/icon.png",
    link: "https://www.innersloth.com/",
    },
    {title: "amongus",
    subtitle: "red sus wtf",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    image: "../src/icon.png",
    link: "https://www.innersloth.com/",
    }
];