export const pastWork= [
    {title: "Gitlet",
    subtitle: "Java and Git",
    description: "Gitlet is a lite version of the Git version control system that can store, update and track files. My java implementation includes branching, merging, and remote pushing and pulling functionality.",
    image: "/src/gitlet.png",
    link: "#past-work",
    },
    {title: "Scheme Interpreter",
    subtitle: "Python and Scheme",
    description: "I built an interpreter in Python implementing the core features of the Scheme dialect of Lisp including a lexer, parser, evaluator, and the frameworks for special methods, including mu methods, which allow for dynamic scoping.",
    image: "/src/scheme.png",
    link: "#past-work",
    },
    {title: "Matrix to Dendrogram",
    subtitle: "Perl and PostScript",
    description: "Matrix to dendrogram is a program that uses computational methods to visualize relationships among RNA structural conformations written in Perl. This was ccomplished by taking data from large matrices (20,000+ entries) of simulated molecular dynamics data and visualizing them as dendrograms using agglomerative hierarchical clustering. Work using this program has been submitted for publication.",
    image: "/src/dendrogram.png",
    link: "#past-work",
    },
    {title: "Assessing Small Molecule Efficacy",
    subtitle: "Fluorescence Assays and PCR",
    description: "I asessed the efficacy and competitiveness of RNA-binding small molecules found by the INFORNA structural analysis platform. Specifically, I assessed a small moleule that targeted miRNA-377, a disease causing RNA related a decrease in blood vessel production following heart failure. Click on this panel to see the published work in Nature Chemistry.",
    image: "/src/inforna.png",
    link: "https://www.nature.com/articles/s41557-020-0514-4",
    }
];